### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by MrToph** [code-423n4/contracts#14]
we need unit tests for all of our contracts. These can be parallelized. If you want to help please assign yourself to one of these, branch off from `master` and create a PR.
Check out the example in `test/TokenLock.spec.ts`

- `C4Governor.sol` (does this need to be tested? at least the parameters should be checked to make sense given our airdrop and token sale pays out 20% immediately)
- `C4TokenSale.sol` (@MrToph #28 )
- `C4Token.sol` (@MrToph #31 )
- `TokenLock.sol` (@HickupHH3 #29 )
- `RevokableTokenLock.sol` (@STYJ #23 )

All PRs should be made to the master branch.

**Comment by STYJ** [comment]
I'd like to do RevokeableTokenLock.sol pls

**Comment by MrToph** [comment]
@STYJ sure, you can have it

**Comment by STYJ** [comment]
Can I get permission to create a branch so I can make a PR?
