### ISSUE TITLE
Merkle proof implementation is subject to tree extension attacks

### ISSUE THREAD

**Issue by Austin-Williams** [code-423n4/contracts#39]
The merkle proof code does not check the _length_ of the proofs, and so it is susceptible to a tree-extension attack (or [second-preimage attack](https://en.wikipedia.org/wiki/Merkle_tree#Second_preimage_attack)).

While this same code has been used in other projects, the key difference here is that the leaf nodes (recipient addresses) have been chosen by wardens (potential adversaries), whereas in other projects the leaf nodes are addresses grabbed from historical blockchain data (_not_ chosen by potential adversaries).

This means a malicious airdrop receiver could have given you a malicious bytes32 "address" which is actually its own merkle root for a tree of addresses that the attacker controls. If you used such a malicious address as a leaf in your merkle tree, it would allow the attacker to generate arbitrarily many valid proofs for addresses they control.

After computing your merkle tree and learning its depth -- and before deploying these contracts -- I recommend adding a `require(merkleProof.length == treeDepth, 'invalid proof')` just above [this line](https://github.com/code-423n4/contracts/blob/main/contracts/ArenaToken.sol#L90).

**Comment by MrToph** [comment]
> While this same code has been used in other projects, the key difference here is that the leaf nodes (recipient addresses) have been chosen by wardens (potential adversaries)

Good point but the leaf nodes are `keccak(recipient, amount)` where the claim amount has been chosen by the C4 team, does this prevent this?

If I understand your attack correctly, the attacker would do:
- h1 = keccak(attacker1, uint256.max)
- h2 = keccak(attacker2, uint256.max)
- h = keccak(h1, h2) and then choose and submit a recipient address such that `h == keccak(recipient, amount)` where `amount` was chosen by the C4 team. They'd need to find a second preimage `(recipient, amount) != (h1, h2)` which goes against the collision resistance of keccak?

**Comment by Austin-Williams** [comment]
Ah okay! As long as the leafs themselves aren't attacker-chosen, then that's fine.
The key is that we don't want an attacker to be able to choose a leaf that is a merkle root of a "bad tree".

Since the leaves are of the form `keccak(<attacker chosen value>, <known public value>`, I think everything is fine in this case!

Because an attacker will be unable to find an `<attacker chosen value>` that will hash out to a value they want (namely their "bad merkle root").

So I think we're actually safe here due to how the leaf values are chosen -- they aren't _actually_ attacker-chosen values.

**Comment by Austin-Williams** [comment]
Okay, I'm sufficiently satisfied that an attacker could not get a "bad merkle root" as a leaf in the tree via the form submission.
